### ISSUE TITLE
Task list version 2.0

### ISSUE THREAD

**Issue by Jzow** [eairps/eairp#118]
This issue is a list of functions that need to be improved, which refers to a plan for the development of business functions to be carried out.

Backend warehouse address: [wansen-erp-api](https://github.com/wansenai/wansen-erp-core)
CC [中文issue计划表](https://github.com/wansenai/wansen-erp/issues/42)

1. System management (Basic)
- [x] User management 
- [x] Role management 
- [x] Department management 
- [x] Menu management 
- [x] System configuration
- [x] #279

2. Retail management (Including data list query and adding/modifying data)
- [x] wansenai/eairp#130
- [x] wansenai/eairp#126

3. Purchasing management
- [x] #162
- [x] #163
- [x] #164

4. Sales management
- [x] #165
- [x] #166
- [x] #167

5. Warehouse management
- [x] #213
- [x] #214
- [x] #215
- [x] #229
- [x] #230

6. Financial management
- [x] #181
- [x] #182
- [x] #209
- [x] #210
- [x] #211
- [x] wansenai/eairp#125

7. Report
- [x] Product inventory report
- [x] Account statistics report
- [x] Retail statistics report
- [x] Procurement statistics report
- [x] Sales statistics report
- [x] Receipt details report
- [x] Outbound details report
- [ ] #240
- [x] Receipt summary report
- [x] Outbound summary report
- [ ] Purchase, sales, and inventory statistics report
- [x] #238
- [x] #239

8. Product management
- [x] wansenai/eairp-web#91
- [x] wansenai/eairp-web#90
- [x] wansenai/eairp-web#92

9. Basic information and data management
- [x] Supplier information
- [x] Customer information
- [x] Member information
- [x] Warehouse information
- [x] wansenai/eairp-web#94
- [x] wansenai/eairp-web#93
- [x] #212

10. Custom plugin (This feature enables users to install customized plugins they want online)
- [ ] Plugin Management

11. GPT3.5 Customized fine-tuning model
 - [x] Model Repository
 - [ ] Model fine-tuning
 
 This is a long plan, and I will do my best and time to quickly develop it. If you see the plan in front of the screen and are interested in contributing code together, then thank you very much. If you have any questions, please feel free to contact me.
 
**September 23, 2023, 16:50 PM Saturday, rainy day**
**Phase II A6 of Xi'an Software R&D Base in Shaanxi, China**
